#!/usr/bin/env bash
# Generates .env.smoke for the emulator-based end-to-end suite.
#
# The RSA key it writes is throwaway and local. The Admin SDK insists on
# parsing *some* valid PEM before it will initialise, but when
# FIRESTORE_EMULATOR_HOST is set it never signs or verifies anything with
# it. Your real service account is never involved.
set -euo pipefail

cd "$(dirname "$0")/.."

if [[ -f .env.smoke ]]; then
  echo ".env.smoke already exists. Delete it first if you want a new one."
  exit 0
fi

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
openssl genrsa -out "$TMP" 2048 2>/dev/null

KEY="$(awk '{printf "%s\\n", $0}' "$TMP")"

cat > .env.smoke <<EOF
# Generated by scripts/make-smoke-env.sh — emulators only, safe to delete.
NEXT_PUBLIC_FIREBASE_API_KEY=demo-key
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=demo-ryder.firebaseapp.com
NEXT_PUBLIC_FIREBASE_PROJECT_ID=demo-ryder
NEXT_PUBLIC_FIREBASE_APP_ID=1:1:web:demo
NEXT_PUBLIC_SITE_NAME=Ryder
NEXT_PUBLIC_USE_EMULATORS=1
FIREBASE_PROJECT_ID=demo-ryder
FIREBASE_CLIENT_EMAIL=smoke@demo-ryder.iam.gserviceaccount.com
FIREBASE_PRIVATE_KEY="${KEY}"
EOF

echo "Wrote .env.smoke. Now run: npm run test:e2e"
